### PR TITLE
Performance improvements for iterating over IDBCursor

### PR DESCRIPTION
**Pull request by kir**
Hello,

   In this pull request, I've added data pre-fetching when iterating over cursor. I.e. for continue() method,
   we take up to 100 records from SQL database and return results from this prefetched data.

   In my system, this gives speedup from 40 seconds to 4 second when loading 800 records from a large table with index (on iPad).

   Thanks,
   KIR

### CODE REVIEW

**Comment by torto** [comment]
Please min version releases.

I have a table with more than two thousand documents.

**Comment by kir** [comment]
@tortoyoyo Sorry, I don't quite understand your comment. What do you mean about 'min version releases'? I do one sql query per 100 records in my patch.

**Comment by kir** [comment]
Hello @DickvdBrink, 

   I've just merged this patch with the latest changes in IndexedDBShim, related to primaryKey fixes.

   Could you please take a look at my changes - what do you think? Is there anything I should do for the patch to be accepted?

  Thanks a lot!

**Comment by DickvdBrink** [comment]
@kir, sorry totally forgot about this. I wanted to try it in our environment because we have some blob fields. I was wondering about memory use in that case. Will look at it Monday or Tuesday. Please just ping here when I didn't respond, I might forget it :)
thanks for the PR!

**Comment by kir** [comment]
Got it, thanks! I'm eager to see how it would work in your environment.

**Comment by DickvdBrink** [comment]
Merged, Thanks a lot! It really feels faster! :)
Sorry for taking so long to merge it.

**Comment by kir** [comment]
Thanks a lot!

**Comment by torto** [comment]
Thank you very much, is much faster: D

**Comment by kir** [comment]
@tortoyoyo Glad it helped you :)

**Pull request merged**
