### PR TITLE
Added missing primaryKey, fixed IDBCursor ranges and IDBIndex count method

### PR DESCRIPTION
**Pull request by ghost**
This also inlcudes #82, #94 and #99.

### CODE REVIEW

**Comment by DickvdBrink** [comment]
Yeah you are right about the keyranges.
Shim is kinda broken without manually applying all patches that's why I created #97 because these issues could have been avoided by testing the shim instead of using for example chrome for executing the tests because then it is using the indexedDB implementation instead of the shim.

Without the patches #94, #99 the shim is totally useless (so I applied them myself).
In my own code I'm also going to apply your commit for the missing primaryKey because I need it now, thanks!

**Comment by ghost** [comment]
> these issues could have been avoided by testing the shim instead of using for example chrome for executing the tests because then it is using the indexedDB implementation instead of the shim.

Yeah this was also bugging me. I'm not familiar with qunit though, will have a look at it. Currently I'm just testing the shim by running my android application which relies on it.

> I'm also going to apply your commit for the missing primaryKey because I need it now, thanks!

No problem, I'm also mashing together all the fixes I can find.

**Comment by ghost** [comment]
All tests completed on android 4.2.1 (stock browser):

**Comment by DickvdBrink** [comment]
It doesn't really matter but next time try to preserve the author information when you apply a patch.
I noticed this in commit e723ccd.

**Comment by ghost** [comment]
Not quite sure how to do that with unmerged pull requests. I referenced them in the description above.

**Comment by DickvdBrink** [comment]
When you append .patch on the end of the URL
https://github.com/axemclion/IndexedDBShim/pull/100.patch you can download a patch.
I did something like curl -G https://github.com/axemclion/IndexedDBShim/pull/100.patch -o 100.patch to download it.
After downloading I did "git am 100.patch --exclude=dist/*"
I needed the exclude because it couldn't merge the .map and .min file.

**Comment by ghost** [comment]
Oh interesting, didn't know about that. Thanks. :)

**Comment by DickvdBrink** [comment]
@elias94xx, I'm testing your code for the primarykey parts. Some of your commits are already merged from different pullrequest so I will skip some of them.
I'm still not really sure about 81d19c50e0f715a60ef3a05f813a384097b7b2f9 so I want to skip that one for now. The reason is the checks for data types (string/number) because it could also be a boolean (not really sure if that is a good idea ;p) and I think it could also be an array when using compound keys.

**Comment by DickvdBrink** [comment]
Primary key path is merged, see 948b105027fab75380054fec04912846847db274!
Thanks @elias94xx

**Pull request closed without merging**
