### PR TITLE
Handle non-IDBKeyRange range objects

### PR DESCRIPTION
**Pull request by mattjacobsen**
If the range parameter is a key range then the cursor's range MUST be set to that range. Otherwise, if the range parameter is a valid key then the cursor's range is set to key range containing only that key value. If the range parameter is not specified, the cursor's key range is left as undefined (http://www.w3.org/TR/IndexedDB/#widl-IDBObjectStore-openCursor-IDBRequest-any-range-IDBCursorDirection-direction).

### CODE REVIEW

**Comment by DickvdBrink** [comment]
Hi @mattjacobsen, sorry for the late reply and thanks for the PR!
The test seems broken after merging this so I can't merge this. See below log.
Does "grunt test" work for you?

```
>> Indexes - Adding data after index is created
>> Message: Could not add data
>> at http://code.jquery.com/qunit/qunit-1.12.0.js:534
>>   at http://localhost:9999/test/IndexTests.js:70
>>   at t (http://localhost:9999/dist/IndexedDBShim.min.js:2)
>>   at r (http://localhost:9999/dist/IndexedDBShim.min.js:2)
>>   at http://localhost:9999/dist/IndexedDBShim.min.js:2

>> Indexes - Index Get
>> Message: Got object from Index Get
>> Actual: undefined
>> Expected: {
>>   "Boolean": true,
>>   "Float": 0.002678917022421956,
>>   "Int": 23,
>>   "String": "Sample Wed Jul 02 2014 13:13:37 GMT+0200 (W. Europe Daylight Tim
e)"
```

**Comment by mattjacobsen** [comment]
Hi @DickvdBrink, sorry I'm only just now getting round to replying.

In short: I ran "grunt test", and it worked.

I then pulled from axemclion/master and merged my changes, after which I noticed that I sometimes got the same errors you described, and sometimes didn't. After much messing around I finally just checked out a clean axemclion/master (58045ea93458ec39c09b7ea680131ef38b254ebc) and found that the errors also appear there. Additionally, at the moment, I'm unable to run grunt on the master without "--force":

<pre><code>
 src\Init.js
      6 |var idbModules = {};
             ^ Redefinition of 'idbModules'.
      8 |var cleanInterface = false;
             ^ Redefinition of 'cleanInterface'.
     16 |                cleanInterface = true;
                         ^ Read only.
   test\DatabaseTests.js
      8 |        dbVersion = dbOpenRequest.result.version || 0;
                 ^ Read only.
   test\sampleData.js
      1 |var DB = {
             ^ Redefinition of 'DB'.
     12 |var sample = (function(){
             ^ Redefinition of 'sample'.
>> 6 errors in 21 files
Warning: Task "jshint:files" failed. Use --force to continue.
Aborted due to warnings.
</pre></code>
<pre>
<code>
>> Indexes - Adding data after index is created
>> Message: Could not add data
>> at http://code.jquery.com/qunit/qunit-1.12.0.js:534
>>   at http://localhost:9999/test/IndexTests.js:70
>>   at b (http://localhost:9999/dist/IndexedDBShim.min.js:3)
>>   at e (http://localhost:9999/dist/IndexedDBShim.min.js:3)
>>   at http://localhost:9999/dist/IndexedDBShim.min.js:3
>> Indexes - Index Get
>> Message: Got object from Index Get
>> Actual: undefined
>> Expected: {
>>   "Boolean": true,
>>   "Float": 0.2189122934360057,
>>   "Int": 49,
>>   "String": "Sample Mon Jul 07 2014 13:37:34 GMT+0200 (W. Europe Summer Time)
"
>> }
>> at http://code.jquery.com/qunit/qunit-1.12.0.js:593
>>   at http://localhost:9999/test/IndexTests.js:125
>>   at b (http://localhost:9999/dist/IndexedDBShim.min.js:3)
>>   at d (http://localhost:9999/dist/IndexedDBShim.min.js:3)
>>   at http://localhost:9999/dist/IndexedDBShim.min.js:3
>> Indexes - Index Get Key
>> Message: Got key from Index Get
>> Actual: undefined
>> Expected: 5
>> at http://code.jquery.com/qunit/qunit-1.12.0.js:556
>>   at http://localhost:9999/test/IndexTests.js:143
>>   at b (http://localhost:9999/dist/IndexedDBShim.min.js:3)
>>   at d (http://localhost:9999/dist/IndexedDBShim.min.js:3)
>>   at http://localhost:9999/dist/IndexedDBShim.min.js:3
>> Indexes - Index update Cursor
>> Message: Cursor expected
>> at http://code.jquery.com/qunit/qunit-1.12.0.js:534
>>   at http://localhost:9999/test/IndexTests.js:186
>>   at b (http://localhost:9999/dist/IndexedDBShim.min.js:3)
>>   at d (http://localhost:9999/dist/IndexedDBShim.min.js:3)
>>   at http://localhost:9999/dist/IndexedDBShim.min.js:3
>>   at http://localhost:9999/dist/IndexedDBShim.min.js:3
Warning: 4/104 assertions failed (7225ms) Used --force, continuing.
Done, but with warnings.
</code>
</pre>

99% of all of this is new to me though, so don't be surprised if the error does lie with me ;-)

**Comment by DickvdBrink** [comment]
Hmz, it seems you are right. After executing the tests multiple times (without your patch) they fail maybe 1 out of 5... 

Haven't tried it yet with your patch but your patch looks like it is working... Will patch it tomorrow I think :)
I will investigate the issue with the flacky tests later, sorry for not seeing this last week.

**Comment by DickvdBrink** [comment]
Merged, thanks for the PR.
The test still fail sometimes on my machine but it isn't because of this commit.. sorry about that.
Thanks!

**Pull request closed without merging**
